Pull request 58: Upd all
Squashed commit of the following:

commit b7c4f8156b50078c8c4ec8c84ddae0239f0125fb
Author: Eugene Burkov <E.Burkov@AdGuard.COM>
Date:   Fri Jul 5 14:36:18 2024 +0300

    bamboo-specs: try omit revision

commit cf4a9c1eed9a92b7acbec3dd59dadeb4bdaeeeef
Author: Eugene Burkov <E.Burkov@AdGuard.COM>
Date:   Fri Jul 5 14:33:22 2024 +0300

    bamboo-specs: try fmt

commit 58e8d406a4c59cc099417d7e06f9ecfcc65f3c59
Author: Eugene Burkov <E.Burkov@AdGuard.COM>
Date:   Fri Jul 5 14:20:18 2024 +0300

    bamboo-specs: rm conditions

commit 4e535474381fb00701ef7b3c976ce77df9c58b0e
Author: Eugene Burkov <E.Burkov@AdGuard.COM>
Date:   Fri Jul 5 14:12:27 2024 +0300

    bamboo-specs: try conditional crutch

commit 1772bd22d303a29001482f931dcd9bdee8bf2888
Author: Eugene Burkov <E.Burkov@AdGuard.COM>
Date:   Fri Jul 5 13:49:13 2024 +0300

    bamboo-specs: try polling

commit 924cf287fa1b2eddb174eef951a3b9909cbdb968
Author: Eugene Burkov <E.Burkov@AdGuard.COM>
Date:   Fri Jul 5 13:46:33 2024 +0300

    all: upd gh, try another spec

commit 27686a228b4c5c4c9b6aec08260af030e26e0918
Author: Eugene Burkov <E.Burkov@AdGuard.COM>
Date:   Fri Jul 5 13:06:35 2024 +0300

    bamboo-specs: try trigger conf

commit 3accac8c09f74622d1ae2a20c900062b90fc8227
Author: Eugene Burkov <E.Burkov@AdGuard.COM>
Date:   Fri Jul 5 12:44:45 2024 +0300

    all: imp specs

diff --git a/bamboo-specs/bamboo.yaml b/bamboo-specs/bamboo.yaml
--- a/bamboo-specs/bamboo.yaml
+++ b/bamboo-specs/bamboo.yaml
@@ -6,12 +6,18 @@
     'name': 'AdGuardDNSClient'
 'variables':
     'dockerFpm': 'alanfranz/fpm-within-docker:ubuntu-bionic'
-    'dockerGo': '${bamboo.adguardRegistryBasePath}/go-builder:1.22.4--1'
+    'dockerGo': 'adguard/go-builder:1.22.5--1'
     'maintainer': 'Adguard DNS Team'
     'name': 'AdGuardDNSClient'
     'channel': 'development'
 
 'stages':
+-
+    'Skip':
+        'manual': false
+        'final': false
+        'jobs':
+        - 'Skip'
 -
     'Lint':
         'manual': false
@@ -37,6 +43,32 @@
         'final': false
         'jobs':
         - 'Publish'
+
+# The Skip stage terminates the plan execution prematurely if the main
+# repository has no changes.  This is needed to avoid builds triggered by
+# changes in the linked repositories, e.g. bamboo-deploy-publisher.
+#
+# TODO(e.burkov):  Remove this crutch, when the Bamboo version will support such
+# a configuration for triggers via YAML specs, see
+# https://docs.atlassian.com/bamboo-specs-docs/8.2.0/specs.html?yaml#triggering-selected-repositories.
+'Skip':
+    'key': 'SKIP'
+    'tasks':
+    -
+        'script':
+        - |-
+          #!/bin/sh
+
+          set -e -f -u -x
+
+          if [ "${bamboo.planRepository.revision}" = "${bamboo.planRepository.previousRevision}" ]
+          then
+              echo "aborting plan due to absent changes"
+
+              exit 0
+          fi
+    'requirements':
+    - 'adg-docker': 'true'
 
 'Lint':
     'docker':
@@ -139,6 +171,11 @@
         'shared': true
         'required': true
     -
+        'name': 'AdGuardDNSClient_windows_arm64_msi'
+        'pattern': '${bamboo.name}/dist/AdGuardDNSClient_windows_arm64.msi'
+        'shared': true
+        'required': true
+    -
         'name': 'Checksums'
         'pattern': '${bamboo.name}/dist/checksums.txt'
         'shared': true
@@ -157,7 +194,7 @@
     'other':
          'clean-working-dir': true
     'requirements':
-      - 'adg-docker': 'true'
+    - 'adg-docker': 'true'
     'tasks':
     -
         'checkout':
@@ -239,7 +276,7 @@
     'other':
          'clean-working-dir': true
     'requirements':
-      - 'adg-docker': 'true'
+    - 'adg-docker': 'true'
     'tasks':
     -
         'checkout':
@@ -296,32 +333,33 @@
 
 'Publish':
     'artifact-subscriptions':
-      - 'artifact': 'AdGuardDNSClient_darwin_amd64'
-      - 'artifact': 'AdGuardDNSClient_darwin_arm64'
-      - 'artifact': 'AdGuardDNSClient_linux_386'
-      - 'artifact': 'AdGuardDNSClient_linux_amd64'
-      - 'artifact': 'AdGuardDNSClient_linux_arm64'
-      - 'artifact': 'AdGuardDNSClient_windows_386'
-      - 'artifact': 'AdGuardDNSClient_windows_386_msi'
-      - 'artifact': 'AdGuardDNSClient_windows_amd64'
-      - 'artifact': 'AdGuardDNSClient_windows_amd64_msi'
-      - 'artifact': 'AdGuardDNSClient_windows_arm64'
-      - 'artifact': 'Checksums'
-      - 'artifact': 'Version'
+    - 'artifact': 'AdGuardDNSClient_darwin_amd64'
+    - 'artifact': 'AdGuardDNSClient_darwin_arm64'
+    - 'artifact': 'AdGuardDNSClient_linux_386'
+    - 'artifact': 'AdGuardDNSClient_linux_amd64'
+    - 'artifact': 'AdGuardDNSClient_linux_arm64'
+    - 'artifact': 'AdGuardDNSClient_windows_386'
+    - 'artifact': 'AdGuardDNSClient_windows_386_msi'
+    - 'artifact': 'AdGuardDNSClient_windows_amd64'
+    - 'artifact': 'AdGuardDNSClient_windows_amd64_msi'
+    - 'artifact': 'AdGuardDNSClient_windows_arm64'
+    - 'artifact': 'AdGuardDNSClient_windows_arm64_msi'
+    - 'artifact': 'Checksums'
+    - 'artifact': 'Version'
     'final-tasks':
-      - 'clean'
+    - 'clean'
     'key': 'PGH'
     'other':
         'clean-working-dir': true
     'requirements':
-      - 'adg-docker': 'true'
+    - 'adg-docker': 'true'
     'tasks':
-      - 'clean'
-      - 'checkout':
-            'repository': 'bamboo-deploy-publisher'
-            'path': 'bamboo-deploy-publisher'
-            'force-clean-build': true
-      - 'script':
+    - 'clean'
+    - 'checkout':
+          'repository': 'bamboo-deploy-publisher'
+          'path': 'bamboo-deploy-publisher'
+          'force-clean-build': true
+    - 'script':
             'interpreter': 'SHELL'
             'scripts':
               - |
@@ -350,7 +388,7 @@
     # images.  The "candidate" pseudo-channel is used to generate version.
     '^rc-v[0-9]+\.[0-9]+\.[0-9]+':
         'variables':
-            'dockerGo': '${bamboo.adguardRegistryBasePath}/go-builder:1.22.4--1'
+            'dockerGo': 'adguard/go-builder:1.22.5-1'
             'channel': 'candidate'
         'stages':
         - 'Lint':
@@ -377,7 +415,7 @@
         # Set the default release channel on the final branch to release, as
         # these are the ones that actually get released.
         'variables':
-            'dockerGo': '${bamboo.adguardRegistryBasePath}/go-builder:1.22.4--1'
+            'dockerGo': 'adguard/go-builder:1.22.5--1'
             'channel': 'release'
         'stages':
         - 'Lint':
@@ -401,9 +439,14 @@
             'jobs':
             - 'Publish'
 -
-    # Don't publish artifacts for other branches.
+    # All the other branches, including master.
     '^.*':
         'stages':
+        - 'Skip':
+            'manual': false
+            'final': false
+            'jobs':
+            - 'Skip'
         - 'Lint':
             'manual': false
             'final': false
@@ -419,6 +462,7 @@
             'final': false
             'jobs':
             - 'ArtifactQA'
+        # Don't publish artifacts for other branches.
 
 'notifications':
 -
